name: Ежедневный коммит

on:
  schedule:
    - cron: '0 6 * * *'  # каждый день в 6 утра по UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Изменить файл
        run: |
          echo "Последний запуск: $(date)" > last-run.txt

      - name: Настроить Git
        run: |
          git config --global user.name "Владимир"
          git config --global user.email "ТВОЙ_EMAIL@пример.com"

      - name: Сделать коммит
        run: |
          git add last-run.txt
          git commit -m "Авто-коммит: $(date)" || echo "Нечего коммитить"
          git push
